//流文件位置
FlowPath=../flow/

//dump目录
DumpPath=../dump/

SyslogPath=../log/Syslog.log

AsyncSyslogPath=./log/AsyncSyslog.log

MDfront1=tcp://:10.3.138.138:11167

//ListenAddr=ssl://0.0.0.0:60005

ListenAddr=tcp://0.0.0.0:50001

//SSLCertFileName=server.crt

//SSLKeyFileName=server.key

#配置交易登陆信息,针对661版本的行情验证
//CTPfront1=tcp://10.3.138.138:11157
#SysBroker=4444
SysUser=7001_admin
SysPassword=7001_admin
OneToMulti_APPID=fixoperation02
OneToMulti_Auth=G795RSM8T31B4Y65

LogLevel=6
