//流文件位置
FlowPath=../flow/

//dump目录
DumpPath=../dump/

SyslogPath=../log/Syslog.log

AsyncSyslogPath=../log/AsyncSyslog.log

//CTPfront1=tcp://180.168.146.187:10001
//setrade6
//CTPfront1=tcp://172.24.125.199:33751

//trade1qq
CTPfront1=tcp://10.3.138.138:11157
//trade1_ccs
//CTPfront1=tcp://172.24.121.41:51057
//trade1qq
//CTPfront1=tcp://172.24.125.212:33157

//neipanse
//CTPfront1=tcp://172.24.121.43:33357

//trade3
//CTPfront1=tcp://172.24.125.198:39333
//neipan
//CTPfront1=tcp://172.24.121.43:33333

//20simnow
//CTPfront1=tcp://218.202.237.33:14030
//simnow7X24
//CTPfront1=tcp://180.168.146.187:10130
//simnow2
//CTPfront1=tcp://218.202.237.33:10102
//CTPfront1=tcp://180.168.146.187:10101
//ListenAddr=ssl://0.0.0.0:61101
ListenAddr=tcp://0.0.0.0:61111
//ListenAddr=tcp://0.0.0.0:41001

//是否自动确认结算单
//0-手动确认，1-自动确认
AutoSettlementConfirm=1

//是否必须填写开平标志
//0-不需要则gw支持填或者不填，不填则自动判断开平；1-需要则不填reject
ForceOpenClose=0

//是否反向开仓.
//0-报单数量超过(持仓-冻结),先平仓,再反向开;1-报单数量超过(持仓-冻结),不平仓,直接反向开仓
ReverseOpen=0

//中继Fix认证信息
//多对多认证信息
MultiToMulti_APPID=fixoperation01
//MultiToMulti_APPID=simnow_client_test
//密文
MultiToMulti_Auth=EP3041GAEZ190H9J
//明文
//MultiToMulti_Auth=BLJTMGONYPRN9A4Q
//MultiToMulti_Auth=0000000000000000

//OneToMulti_APPID=fixoperation02
//密文
//OneToMulti_Auth=G795RSM8T31B4Y65
//明文
//OneToMulti_Auth=WHJRIZR1W7LIMJYS


//MultiToMulti_APPID=fixmtom
//MultiToMulti_Auth=ZEDP42QEE02FH5SU

//OneToMulti_APPID=fix1tom
//OneToMulti_Auth=GZM2UK5KEPBN3O4P

//客户端认证是否解密
//针对数据库表导出的数据必须解密.如发布客户使用加解密方式不一样,设置为0
DecodeAuth=1

SysBroker=4444
SysUser=4444_admin
SysPassword=4444_admin
SysElapse=1

Language=1

#日志级别设置
#NONE      = 0
#EMERGENCY = 1
#CRITICAL  = 2
#ERROR     = 3
#WARNING   = 4
#INFO      = 5
#DEBUG     = 6
LogLevel=6
