ConfigPath=../config/
FlowPath=../flow/
SyslogPath=../log/Syslog.log
//交易所
ExchangeID=INE
//会员号
ParticipantID=0007
//席位
TraderID=0007c3c
#FrontAddr=tcp://192.168.11.31:4903
#FrontAddr=tcp://192.168.12.41:4903
#FrontAddr=tcp://192.168.16.31:4903
FrontAddr=tcp://172.24.120.132:26171

//一档501，五档500
MDTopic=5001

//本席位的安装编号
InstallID=1

//报盘管理器ID
OMServerItem=1

///交易平台产品信息
UserProductInfo=SFTP V1.0

//是否使用fens
UseFens=yes

