//配置路径
ConfigPath=../config/

//流文件路径
FlowPath=../flow/

//dump目录
DumpPath=../dump/

//Syslog路径
SyslogPath=../log/Syslog.log

//交易所
ExchangeID=INE

//会员号
ParticipantID=0007

//席位号
TraderID=0007c3c

///该交易员内部编号
InstallID=1

///报盘机管理器编号
OMServerItem=1

///是否使用历史持仓。上期所缺省使用历史持仓;
#UseHistoryPosition=no

//地址
#ExchangeAddress=tcp://192.168.11.31:4901
#ExchangeAddress=tcp://192.168.12.41:4901
#ExchangeAddress=tcp://192.168.16.31:4901
ExchangeAddress=tcp://172.24.120.132:26181

///API用户产品信息
UserProductInfo=SFTP V1.0

///API接口产品信息
InterfaceProductInfo=V1.02

///API协议信息
ProtocolInfo=ftd

#UseFens=no
UseFens=yes

UseBizStatusLog=yes
UseBizOperationLog=yes
UseBizExceptionLog=yes
UseNetStatusLog=no
UseNetConnectLog=yes
UseNetIOLog=yes
UseNetPackageLog=yes
UseNetCompressLog=yes
UseNetExceptionLog=yes
UseProcessLog=yes

//对话流每秒发送上限
DialogMaxPerSecond=10

//在途对话流上限
DialogMaxUnfinished=10

