//配置信息
ConfigPath=../config/

//本地流文件地址
FlowPath=../flow/

//Syslog路径
SyslogPath=../log/Syslog.log

//交易所地址，可以配置多个
//SFIT SHFE TEST 25trade1 fens
//FrontAddr=tcp://172.16.126.25:4903
//FrontAddr=tcp://172.16.126.25:4907

//FrontAddr=tcp://172.19.125.70:57025
//Option Test
//FrontAddr=tcp://172.19.125.71:57125
FrontAddr=tcp://172.24.120.132:26171
//FrontAddr=tcp://172.24.120.132:26171
//FrontAddr=tcp://172.24.121.50:33011
// Fens Test
//FrontAddr=tcp://172.19.125.70:4903

//席位
ExchangeID=SHFE
ParticipantID=0006
TraderID=0006c2c

//本席位的安装编号
InstallID=1

//行情主题
MDTopic=1001

///交易平台产品信息
UserProductInfo=SFTP V1.0

//报盘管理器ID
OMServerItem=1

UseFens=no
#UseFens=yes
