# -*- coding:utf-8 -*-
"""
FIX tag constants used in the automated testing framework.
All tag numbers used across FixInitiator.py are defined here
as named constants for readability and maintainability.
"""

# Standard FIX tags
TAG_MSG_TYPE = '35'
TAG_SENDER_COMP_ID = '49'
TAG_TARGET_COMP_ID = '56'
TAG_MSG_SEQ_NUM = '34'
TAG_SENDER_SUB_ID = '50'
TAG_POSS_DUP_FLAG = '43'

TAG_ACCOUNT = '1'
TAG_CL_ORD_ID = '11'
TAG_ORIG_CL_ORD_ID = '41'
TAG_ORDER_ID = '37'
TAG_EXEC_ID = '17'
TAG_EXEC_TYPE = '150'
TAG_ORD_STATUS = '39'

TAG_SYMBOL = '55'
TAG_SIDE = '54'
TAG_PRICE = '44'
TAG_ORDER_QTY = '38'
TAG_ORD_TYPE = '40'
TAG_TIME_IN_FORCE = '59'
TAG_STOP_PX = '99'
TAG_MIN_QTY = '110'
TAG_HANDL_INST = '21'
TAG_OPEN_CLOSE = '77'
TAG_PAY_DATE = '432'
TAG_SECURITY_EXCHANGE = '207'
TAG_TRANSACT_TIME = '60'

TAG_ON_BEHALF_OF_SUB_ID = '116'
TAG_BEGIN_STRING = '8'
TAG_BODY_LENGTH = '9'
TAG_CHECKSUM = '10'

TAG_NO_PARTY_IDS = '453'
TAG_PARTY_ID = '448'
TAG_PARTY_ROLE = '452'

TAG_QUOTE_ID = '117'
TAG_QUOTE_REQ_ID = '131'
TAG_QUOTE_MSG_ID = '1166'
TAG_QUOTE_CANCEL_TYPE = '298'
TAG_QUOTE_SET_ID = '302'
TAG_TOT_NO_QUOTE_ENTRIES = '304'
TAG_NO_QUOTE_ENTRIES = '295'
TAG_QUOTE_ENTRY_ID = '299'
TAG_BID_PX = '132'
TAG_BID_SIZE = '134'
TAG_OFFER_PX = '133'
TAG_OFFER_SIZE = '135'
TAG_OPEN_CLOSE_QTY = '77'

TAG_MD_REQ_ID = '262'
TAG_SUB_REQ_TYPE = '263'
TAG_MARKET_DEPTH = '264'
TAG_MD_UPDATE_TYPE = '265'
TAG_NO_RELATED_SYM = '146'

TAG_SECURITY_REQ_ID = '320'
TAG_SECURITY_REQ_TYPE = '321'
TAG_SECURITY_GROUP = '1151'

TAG_POS_REQ_ID = '710'
TAG_POS_TRANS_TYPE = '709'
TAG_POS_MAINT_ACTION = '712'
TAG_CLEARING_BUS_DATE = '715'
TAG_POS_TYPE = '703'
TAG_LONG_QTY = '704'
TAG_ORIG_POS_REQ_REF_ID = '713'
TAG_POS_MAINT_RPT_REF_ID = '714'
TAG_POS_MAINT_RPT_ID = '721'
TAG_NO_POSITIONS = '702'
TAG_NO_POS_AMT = '711'

TAG_NEW_SEQ_NO = '36'
TAG_BEGIN_SEQ_NO = '7'

# Custom/Chinese futures exchange tags
TAG_HEDGE_FLAG = '20001'
TAG_20002 = '20002'
TAG_20003 = '20003'
TAG_FRONT_ID = '20004'
TAG_SESSION_ID = '20005'
TAG_20006 = '20006'
TAG_20009 = '20009'
TAG_20011 = '20011'
TAG_200011 = '200011'

# Special OnBehalfOfSubID (tag 116) values for message routing
ON_BEHALF_LOGON_REQUEST = '12288'
ON_BEHALF_LOGON_SUCCESS = '12289'
ON_BEHALF_OPTION_SELF_HEDGE_ORDER = '16436'
ON_BEHALF_OPTION_SELF_HEDGE_CANCEL = '16438'
ON_BEHALF_POSITION_EXECUTION_REPORT = '16422'

# MsgType values
MSGTYPE_LOGON = 'A'
MSGTYPE_LOGOUT = '5'
MSGTYPE_HEARTBEAT = '0'
MSGTYPE_NEW_ORDER_SINGLE = 'D'
MSGTYPE_ORDER_CANCEL_REQUEST = 'F'
MSGTYPE_ORDER_CANCEL_REPLACE_REQUEST = 'G'
MSGTYPE_ORDER_STATUS_REQUEST = 'H'
MSGTYPE_MASS_QUOTE = 'i'
MSGTYPE_QUOTE_CANCEL = 'Z'
MSGTYPE_MARKET_DATA_REQUEST = 'V'
MSGTYPE_NEW_ORDER_MULTILEG = 'AB'
MSGTYPE_SECURITY_DEFINITION_REQUEST = 'c'
MSGTYPE_POSITION_MAINTENANCE_REQUEST = 'AL'
MSGTYPE_EXECUTION_REPORT = '8'
MSGTYPE_ORDER_CANCEL_REJECT = '9'
MSGTYPE_SEQUENCE_RESET = '4'
MSGTYPE_RESEND_REQUEST = '2'
MSGTYPE_REJECT = '3'

# Parties sub-tags within tag 453 groups
TAG_PARTY_ID_1 = '448'
TAG_PARTY_ROLE_1 = '452'
TAG_PARTY_ID_2 = '4481'
TAG_PARTY_ROLE_2 = '4521'
